### ISSUE TITLE
Rerender can lead to duplicate elements

### ISSUE THREAD

**Issue by beevelop** [gatewayapps/react-adaptivecards#10]
Right now, the AdaptiveCard is **appended** to the final `div` every time, the component renders. Trying to combine this library with the `react-chat-widget`'s `renderCustomComponent` led in my case to the AdaptiveCard being rendered twice or more (Meeseeks style).

https://github.com/gatewayapps/react-adaptivecards/blob/master/src/index.js#L96
```jsx
return <div style={this.props.style} ref={(n) => { n && n.appendChild(result) }} />
```

I'm not quite sure if this is the best approach to tackle this behaviour, but I tried it with checking for the node's `firstChild` and removing it (if it exists) prior to appending the AdaptiveCard again:
```js
n.firstChild && n.removeChild(n.firstChild);
n.appendChild(result);
```

Does this behaviour / approach make sense to you? Or might this even be caused by a bad rerender strategy of `react-chat-widget`?

Edit: Have to say, that the end result (no duplicates) seems to be working properly with the above hack.

**Comment by mastasky** [comment]
This issue still seems to be present.

**Comment by l-Marty-l** [comment]
Yes, I'm using this in my SPFX web part on SharePoint online and I recognized this issue when I edit and re-published. There were no commits to this since March 2018. :(

**Comment by FreezeBerries** [comment]
I had to use this library for work and figured out a quick fix. On line 125 in index.js
`            if (n && !n.firstChild) {
              n.appendChild(result);
            }`

The resulting try block:

`try {
        this.adaptiveCard.parse(this.props.payload);
        var result = this.adaptiveCard.render();
        return _react2.default.createElement('div', { style: this.props.style, ref: function ref(n) {
            if (n && !n.firstChild) {
              n.appendChild(result);
            }
          } });
      }`

**Comment by jimmywim** [comment]
So my workaround for this, without modifying the underlying code (because I'm in TSX and didn't wanna try and port it and type it properly, etc) - was to first reset the state property that represents my card (set it back to an empty string via setState), then to re-fetch it (as I need to get the latest card's json after a submit action anyway) and set it back into state with setState.

My render method has a check around `this.state.cardJson` so it doesn't render at all if the cardJson string is empty. When it's refetched, the cardJson string is present then renders.

My render looks like this:

```
  public render() {
    if (this.state.cardJson) {
      const card = <AdaptiveCard
        payload={this.state.cardJson}
        onActionSubmit={this.submitClicked}
      />;

      return (
        <div>
          {card}
        </div>
      );
    }
    else {
      return <div></div>;
    }
  }
```

It does cause a flash, but as my action opens a new window (then calls an API method to update the base object's state) the flash isn't noticeable (as it happens on the other browser tab).

**Comment by GariaHarish** [comment]
There should work n.replaceWith(results)

**Comment by michal-turzynski** [comment]
@GariaHarish Changing the below [line of code](https://github.com/gatewayapps/react-adaptivecards/blob/0f0e78c660cb059241e043280aa4688949eaa3a9/src/index.js#L96):
`return <div style={this.props.style} ref={(n) => { n && n.appendChild(result) }} />`
to:
`<div style={this.props.style} ref={(n) => { n && n.replaceWith(result) }} />`
worked for me. Thanks!
